import * as React from 'react';
import {Metadata} from 'next';
import MainLayout from '@/layout/layout';

export const metadata: Metadata = {
    title: 'Next App',
    description: 'Generated by create next app'
};


export default function RootLayout({
                                       children
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <>
            <MainLayout>
                {children}
            </MainLayout>
        </>
    );
}

